version: "3.9"
services:
  migrator:
    container_name: messaging-gateway-migrator
    image: ghcr.io/canpok1/messaging-gateway/migrator:latest
    env_file:
      - ".env"
    command: ["migrate-up"]

  server:
    container_name: messaging-gateway-server
    image: ghcr.io/canpok1/messaging-gateway/server:latest
    environment:
      - APP_NAME=messaging-gateway-notifier-prd
      - LOG_LEVEL=info
    env_file:
      - ".env"
    restart: always

networks:
  default:
    external:
      name: common-database-network
