version: "3.9"
services:
  migrate:
    image: ghcr.io/canpok1/messaging-gateway/migrator:latest
    env_file:
      - ".env"
    command: ["migrate-up"]

  server:
    image: ghcr.io/canpok1/messaging-gateway/server:latest
    env_file:
      - ".env"
    restart: always

networks:
  default:
    external:
      name: common-database-network
