version: "3.9"
services:
  dev:
    container_name: messaging-gateway_dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      NODE_OPTIONS: "--enable-source-maps"

    volumes:
      - ..:/workspaces:cached

    command: /bin/sh -c "while sleep 1000; do :; done"

    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: messaging-gateway_db
    image: "mariadb:11.4"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    env_file:
      - "db.env"
    volumes:
      - "db-store:/var/lib/mysql"
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      start_period: "10s"
      interval: "10s"
      retries: 30
volumes:
  db-store:

