FROM node:24

ENV TZ=Asia/Tokyo

ENV TBLS_VERSION=1.76.1
ENV MIGRATE_VERSION=4.17.1
RUN curl -o tbls.deb -L https://github.com/k1LoW/tbls/releases/download/v$TBLS_VERSION/tbls_$TBLS_VERSION-1_arm64.deb \
  && dpkg -i tbls.deb \
  && rm tbls.deb \
  && curl -o migrate.deb -L https://github.com/golang-migrate/migrate/releases/download/v$MIGRATE_VERSION/migrate.linux-arm64.deb \
  && dpkg -i migrate.deb \
  && rm migrate.deb

RUN apt update && apt install -y \
  fonts-ipafont-gothic \
  fonts-ipafont-mincho \
  redis-tools
